name: Build complex-client

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./complex/complex-client
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print current path
        run: |
          pwd
          ls -al

      - name: Build client image
        run: |
          docker build \
            -t harry1991/complex-client \
            -t harry1991/complex-client:${{github.sha}} \
            -f docker/Dockerfile \
            .

      - name: Signin to docker
        run: docker login -u ${{secrets.DOCKER_USER_NAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Push image to docker hub
        run: docker push --all-tags harry1991/complex-client
