name: Deploy multi-container application (complex)

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./complex
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print current path
        run: |
          pwd
          ls -al
      
      - name: Build test image
        run: |
          docker build \
            -t harry1991/complex-client-test \
            -f complex-client/docker/Dockerfile.development \
            ./complex-client

      - name: Run test
        run: |
          docker run \
            -e CI=true \
            harry1991/complex-client-test \
            yarn test

  build-client:
    needs: [test]
    uses: ./.github/workflows/build-complex-client.yml

  build-server:
    needs: [test]
    uses: ./.github/workflows/build-complex-server.yml

  build-nginx:
    needs: [test]
    uses: ./.github/workflows/build-complex-nginx.yml

  build-worker:
    needs: [test]
    uses: ./.github/workflows/build-complex-worker.yml

  release:
    needs: [build-client, build-server, build-nginx, build-worker]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./complex
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print current path
        run: |
          pwd
          ls -al

      - name: Generate deployment package
        run: zip -r deploy.zip . -x ./node_modules/\*

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_key: ${{secrets.AWS_ACCESS_KEY_PASSWORD}}
          application_name: multi-container-app
          environment_name: Multicontainerapp-env
          existing_bucket_name: elasticbeanstalk-ap-northeast-2-268758655568
          region: ap-northeast-2
          version_label: ${{github.sha}}
          deployment_package: ./complex/deploy.zip
